spring.application.name=HotelBooking
spring.profiles.active=dev

# Global Optimization Settings
spring.threads.virtual.enabled=true
spring.docker.compose.enabled=false

# Media Server File Upload Paths
media.server-path=C:/hotel-booking-backend/uploads/
media.base-uri=http://localhost:8080/api/medias/download/

spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG