# Local Dev Database Config
spring.datasource.driver-class-name=org.postgresql.Driver
# JWT Configuration
app.jwt.secret=${JWT_SECRET:zR4vK9wX8bY1c7dQ2eN5m6pQ3rT8uW1xY4zA7bC0dE3fG6hI9jK2lM5nO8pQ1rS}
jwt.expiration=86400000

# Database Configuration (Example)
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5433/hotelbooking}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:qwer}

# Dev JPA Console Logging Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Media Server File Upload Paths
media.server-path=C:/hotel-booking-backend/uploads/
media.base-uri=http://localhost:8080/api/medias/download/

logging.level.org.hibernate.SQL=DEBUG