apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-backend
  namespace: hotel-booking
  labels:
    app: spring-backend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: spring-backend
  template:
    metadata:
      labels:
        app: spring-backend
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: spring-backend
          image: REPOSITORY/IMAGE_NAME:TAG
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          startupProbe:
            tcpSocket:
              port: 8080
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-env
                  key: JWT_SECRET
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-env
                  key: DATABASE_URL
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-env
                  key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-env
                  key: DATABASE_PASSWORD
